# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCb7t9UeVXUEoxbGGSuzyRe7Fwc-zOxH
"""

import numpy as np
import matplotlib.pyplot as plt

# Aircraft and atmospheric parameters
S = 20
Cl = 0.6
Cd = 0.03
a = 343

rho_sea = 1.225
rho_alt = 0.9

# Velocity range
velocities = np.linspace(30, 250, 100)

# Original calculations
lift_sea = []
drag_sea = []
lift_alt = []
mach = []

for V in velocities:
    lift_sea.append(0.5 * rho_sea * V**2 * S * Cl)
    drag_sea.append(0.5 * rho_sea * V**2 * S * Cd)
    lift_alt.append(0.5 * rho_alt * V**2 * S * Cl)
    mach.append(V / a)

# Original lift graph
plt.figure()
plt.plot(velocities, lift_sea)
plt.title("Lift vs Velocity (Sea Level)")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Lift (N)")
plt.grid()
plt.savefig("lift.png")
plt.show()

# Original drag graph
plt.figure()
plt.plot(velocities, drag_sea)
plt.title("Drag vs Velocity (Sea Level)")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Drag (N)")
plt.grid()
plt.savefig("drag.png")
plt.show()

# Original Mach graph
plt.figure()
plt.plot(velocities, mach)
plt.axhline(1, linestyle="--")
plt.title("Mach Number vs Velocity")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Mach number")
plt.grid()
plt.savefig("mach.png")
plt.show()

# Original altitude comparison
plt.figure()
plt.plot(velocities, lift_sea, label="Sea Level")
plt.plot(velocities, lift_alt, label="Altitude")
plt.title("Lift vs Velocity (Altitude Effect)")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Lift (N)")
plt.legend()
plt.grid()
plt.savefig("altitude.png")
plt.show()

# --------------------------------------------------
# NEW EXPERIMENT: Effect of Wing Area
# --------------------------------------------------

wing_areas = [10, 20, 30]

plt.figure()

for wing_area in wing_areas:
    lift_wing_area = []

    for V in velocities:
        lift = 0.5 * rho_sea * V**2 * wing_area * Cl
        lift_wing_area.append(lift)

    plt.plot(
        velocities,
        lift_wing_area,
        label=f"Wing area = {wing_area} m²"
    )

plt.title("Effect of Wing Area on Lift")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Lift (N)")
plt.legend()
plt.grid()
plt.savefig("wing_area.png")
plt.show()



# --------------------------------------------------
# NEW EXPERIMENT: Effect of Lift Coefficient
# --------------------------------------------------

lift_coefficients = [0.3, 0.6, 0.9]

plt.figure()

for lift_coefficient in lift_coefficients:
    lift_cl = []

    for V in velocities:
        lift = 0.5 * rho_sea * V**2 * S * lift_coefficient
        lift_cl.append(lift)

    plt.plot(
        velocities,
        lift_cl,
        label=f"Cl = {lift_coefficient}"
    )

plt.title("Effect of Lift Coefficient on Lift")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Lift (N)")
plt.legend()
plt.grid()
plt.savefig("lift_coefficient.png")
plt.show()






# --------------------------------------------------
# NEW EXPERIMENT: Effect of Drag Coefficient
# --------------------------------------------------

drag_coefficients = [0.015, 0.03, 0.045]

plt.figure()

for drag_coefficient in drag_coefficients:
    drag_cd = []

    for V in velocities:
        drag = 0.5 * rho_sea * V**2 * S * drag_coefficient
        drag_cd.append(drag)

    plt.plot(
        velocities,
        drag_cd,
        label=f"Cd = {drag_coefficient}"
    )

plt.title("Effect of Drag Coefficient on Drag")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Drag (N)")
plt.legend()
plt.grid()
plt.savefig("drag_coefficient.png")
plt.show()